### ISSUE TITLE
要是能变成一个在Chrome商店上架的扩展就好了。

### ISSUE THREAD

**Issue by fzhw88** [icefate/Telescape#1]
有这个功能需求，但是现在的Chrome调试模式很烦人，不知道这个插件能否做成一个在商店商家的扩展？

**Comment by icefate** [comment]
@fzhw88 win7可以设置组策略屏蔽Chrome反复提示“请停用以开发者模式运行的扩展程序” 。 参考：https://www.zhihu.com/question/24027794/answer/34426149
